// Code generated by P2B. DO NOT EDIT.

package model

import (
	"time"

	"github.com/uptrace/bun"
)

type Role string

const (
	RoleUser  Role = "USER"
	RoleAdmin Role = "ADMIN"
)

type User struct {
	bun.BaseModel `bun:"table:User"`

	ID        int       `bun:"id,nullzero,pk,notnull"`
	Name      string    `bun:"name,nullzero"`
	Email     string    `bun:"email,nullzero,notnull,unique"`
	CreatedAt time.Time `bun:"created_at,nullzero,notnull"`
	Role      Role      `bun:"role,nullzero,notnull"`
}
