// Code generated by P2B. DO NOT EDIT.

package model

import (
	"time"

	"github.com/uptrace/bun"
)

type Role string

const (
	RoleUser  Role = "USER"
	RoleAdmin Role = "ADMIN"
)

type User struct {
	bun.BaseModel `bun:"table:User"`

	ID        int       `bun:"id,nullzero,pk,notnull"`
	Name      string    `bun:"name,nullzero"`
	Email     string    `bun:"email,nullzero,notnull,unique"`
	CreatedAt time.Time `bun:"created_at,nullzero,notnull"`
	Role      Role      `bun:"role,nullzero,notnull"`
	Posts     []Post    `bun:"rel:has-many"`
}

type Post struct {
	bun.BaseModel `bun:"table:posts"`

	ID        int       `bun:"id,nullzero,pk,notnull"`
	CreatedAt time.Time `bun:"created_at,nullzero,notnull"`
	UpdatedAt time.Time `bun:"updated_at,nullzero,notnull"`
	Published bool      `bun:"published,nullzero,notnull"`
	Title     string    `bun:"title,nullzero,notnull"`
	Author    User      `bun:"rel:belongs-to,join:authorId=id"`
	AuthorID  int       `bun:"author_id,nullzero,notnull"`
}
