// Code generated by P2B. DO NOT EDIT.

package model

import (
	"time"

	"github.com/uptrace/bun"
)

type Role string

const (
	RoleUser  Role = "USER"
	RoleAdmin Role = "ADMIN"
)

type User struct {
	bun.BaseModel `bun:"table:User"`

	ID        int       `bun:"id,pk,nullzero"`
	Name      string    `bun:"name,nullzero"`
	Email     string    `bun:"email,notnull,unique,nullzero"`
	CreatedAt time.Time `bun:"created_at,notnull,nullzero"`
	Role      Role      `bun:"role,notnull,nullzero"`
	Posts     []Post    `bun:"rel:has-many"`
}

type Post struct {
	bun.BaseModel `bun:"table:posts"`

	ID        int       `bun:"id,pk,nullzero"`
	CreatedAt time.Time `bun:"created_at,notnull,nullzero"`
	UpdatedAt time.Time `bun:"updated_at,notnull,nullzero"`
	Published bool      `bun:"published,notnull,nullzero"`
	Title     string    `bun:"title,notnull,nullzero"`
	Author    User      `bun:"rel:belongs-to,join:author_id=id"`
	AuthorID  int       `bun:"author_id,notnull,nullzero"`
}

type Like struct {
	bun.BaseModel `bun:"table:Like"`

	UserID int `bun:"user_id,pk,nullzero"`
	PostID int `bun:"post_id,pk,nullzero"`
}
